<a href="https://colab.research.google.com/github/Nimira43/Deep-Learning-Pytorch/blob/main/funds_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Matrix Multiplication

Two ways:

* Element wise multiplication
* Matrix multiplication - dot product

In [1]:
import torch

In [3]:
#Element wise

set1 = torch.tensor([1, 2, 3])
set1

tensor([1, 2, 3])

In [4]:
set2 = torch.tensor([3, 4, 8])
set2

tensor([3, 4, 8])

In [5]:
print(set1, " * ", set2)
print(f"Equal: {set1 * set2}")

tensor([1, 2, 3])  *  tensor([3, 4, 8])
Equal: tensor([ 3,  8, 24])


In [6]:
# Matrix multiplication

torch.matmul(set1, set2)

tensor(35)

Visualised

1 * 3 + 2 * 4 + 3 * 8

3 + 8 + 24

= 35


Example 2

In [7]:
print(set1, " * ", set1) # element wise
print(f"Equal: {set1 * set1}")

tensor([1, 2, 3])  *  tensor([1, 2, 3])
Equal: tensor([1, 4, 9])


In [8]:
torch.matmul(set1, set1) # matrix multiplication - matmul

tensor(14)

In [9]:
%%time
value = 0
for i in range(len(set1)):
  value += set1[i] * set1[i]
value #element wise

CPU times: user 0 ns, sys: 864 µs, total: 864 µs
Wall time: 5.13 ms


tensor(14)

In [10]:
%%time
torch.matmul(set1, set1) #matmul

CPU times: user 75 µs, sys: 0 ns, total: 75 µs
Wall time: 78.4 µs


tensor(14)

Dimensions

Inner dimension must match

(3, 2) @ (2, 3) ok

(2, 3) @ (3, 2) ok

(3, 2) @ (3, 2) error

resulting tensor has the shape of the outer dimension

(3, 2) @ (2, 3) results in a (3, 3) tensor

(2, 3) @ (3, 2) results in a (2, 2) tensor


In [13]:
torch.matmul(torch.rand(3, 2), torch.rand(3, 2))

RuntimeError: ignored

In [14]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[0.3206, 0.2857, 0.6435],
        [0.6178, 0.4648, 1.0947],
        [0.6030, 0.2815, 0.7765]])

In [15]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[0.6354, 0.3647],
        [0.8047, 0.5695]])

matrixmultiplication.xyz


In [30]:
ten1 = torch.tensor([[4, 8, 2],
                     [5, 2, 7],
                     [3, 9, 1]])

In [31]:
ten2 = torch.tensor([[5, 8, 1],
                     [2, 5, 4]])

In [32]:
ten3 = torch.tensor([[2, 7, 5],
                     [4, 1, 9]])

In [33]:
ten4 = torch.tensor([[2, 8],
                     [9, 3]])

In [34]:
ten5 = torch.tensor([[6, 5],
                     [8, 4],
                     [7, 5]])

In [35]:
ten6 = torch.tensor([[2, 6],
                     [7, 8],
                     [3, 1]])

In [36]:
ten1.ndim, ten1.shape

(2, torch.Size([3, 3]))

In [37]:
ten2.ndim, ten2.shape

(2, torch.Size([2, 3]))

In [70]:
ten3.ndim, ten3.shape

(2, torch.Size([2, 3]))

In [40]:
ten4.ndim, ten4.shape

(2, torch.Size([2, 2]))

In [46]:
ten5.ndim, ten5.shape

(2, torch.Size([3, 2]))

In [47]:
ten6.ndim, ten6.shape

(2, torch.Size([3, 2]))

In [48]:
torch.mm(ten2, ten6)

tensor([[69, 95],
        [51, 56]])

In [72]:
torch.mm(ten6, ten3)

tensor([[ 28,  20,  64],
        [ 46,  57, 107],
        [ 10,  22,  24]])

In [50]:
torch.mm(ten3, ten1)

tensor([[ 58,  75,  58],
        [ 48, 115,  24]])

ten1 = torch.tensor

([[4, 8, 2],

  [5, 2, 7],

  [3, 9, 1]])

ten2 = torch.tensor

([[5, 8, 1],

  [2, 5, 4]])

ten3 = torch.tensor

([[2, 7, 5],

  [4, 1, 9]])

ten4 = torch.tensor

([[2, 8],

  [9, 3]])

ten5 = torch.tensor

([[6, 5],

  [8, 4],

  [7, 5]])

ten6 = torch.tensor

([[2, 6],

  [7, 8],

  [3, 1]])



Transpose

In [73]:
ten5.T

tensor([[6, 8, 7],
        [5, 4, 5]])

In [52]:
ten2.T


tensor([[5, 2],
        [8, 5],
        [1, 4]])

In [74]:
ten3, ten3.shape

(tensor([[2, 7, 5],
         [4, 1, 9]]),
 torch.Size([2, 3]))

In [56]:
ten3.T, ten3.T.shape

(tensor([[2, 4],
         [7, 1],
         [5, 9]]),
 torch.Size([3, 2]))

In [65]:
torch.matmul(ten2, ten3.T)

tensor([[71, 37],
        [59, 49]])

In [66]:
setX = torch.tensor([[4, 3, 5],
                     [4, 2, 9]])

setY = torch.tensor([[2, 3, 5],
                     [8, 4, 2]])

In [76]:
setX.T

tensor([[4, 4],
        [3, 2],
        [5, 9]])

In [67]:
setX.shape, setY.shape

(torch.Size([2, 3]), torch.Size([2, 3]))

In [68]:
torch.matmul(setX.T, setY)

tensor([[40, 28, 28],
        [22, 17, 19],
        [82, 51, 43]])

In [75]:
#The matrix multiplication operation works when setX is transposed
print(f"original shapes: setX = {setX.shape}, setY = {setY.shape}")
print(f"new shapes: setX = {setX.T.shape}, setY = {setY.shape}")
print(f"Multiplying: {setX.T.shape} @ {setY.shape} <- inner dims must match")
print(f"Output: \n")
output = torch.matmul(setX.T, setY)
print(output)
print(f"\nResulting output shape: {output.shape} ")

original shapes: setX = torch.Size([2, 3]), setY = torch.Size([2, 3])
new shapes: setX = torch.Size([3, 2]), setY = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dims must match
Output: 

tensor([[40, 28, 28],
        [22, 17, 19],
        [82, 51, 43]])

Resulting output shape: torch.Size([3, 3]) 
